export class Pet {
    id: String;
    name: String;
    lost: boolean;

    constructor() {
        //id auto generated by JPA
        this.id="";
        this.name="";
        this.lost=false;
    }
}